/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import clase.CFormulaArma;
import clase.CParametro;
import clase.CSistema;
import java.awt.event.ItemEvent;
import static java.lang.System.console;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.util.Locale;

import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;
import javax.swing.JOptionPane;

import javax.swing.JTextArea;

/**
 *
 * @author assendofr
 */
public class Formula extends javax.swing.JFrame {

    CSistema objs;
    JTextArea txFormula;
    String FormulaValida = "";

    /**
     * Creates new form Formula
     */
    public Formula(CSistema objs, JTextArea txFormula) {
        initComponents();
        this.objs = objs;
        this.txFormula = txFormula;
        this.jTextAreaIni.setText(txFormula.getText());
        this.jTextAreaEdit.setText(txFormula.getText());
        Cargar();
    }

    public void Cargar() {
        String strMsg = "";

        try {

            //llenar combo tipo
            CParametro objt = new CParametro(0, "", 0, "", 0);
            objt.LLenarParametro();
            String strDato = "";

            this.cmbparametro.addItem("");
            for (int x = 0; x < objt.strDatosCombo.length; x++) {
                strDato = objt.strDatosCombo[x];
                cmbparametro.addItem(strDato);
            }

        } catch (Exception ex) {
            strMsg = ex.getMessage();
            //JOptionPane.showMessageDialog(null, strMsg);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaIni = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaEdit = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bumas = new javax.swing.JButton();
        bumenos = new javax.swing.JButton();
        bupor = new javax.swing.JButton();
        budiv = new javax.swing.JButton();
        busqrt = new javax.swing.JButton();
        bupot = new javax.swing.JButton();
        bulog = new javax.swing.JButton();
        buparcua = new javax.swing.JButton();
        buparred = new javax.swing.JButton();
        buguardar = new javax.swing.JButton();
        buCalcula = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTot = new javax.swing.JTextArea();
        cmbparametro = new javax.swing.JComboBox<>();
        bupi = new javax.swing.JButton();
        bucond = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jTextAreaIni.setEditable(false);
        jTextAreaIni.setColumns(20);
        jTextAreaIni.setRows(5);
        jScrollPane3.setViewportView(jTextAreaIni);

        jTextAreaEdit.setColumns(20);
        jTextAreaEdit.setRows(5);
        jScrollPane4.setViewportView(jTextAreaEdit);

        jLabel1.setText("Formula");

        jLabel2.setText("Operadores Aritmeticos");

        bumas.setText("+");
        bumas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bumasActionPerformed(evt);
            }
        });

        bumenos.setText("--");
        bumenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bumenosActionPerformed(evt);
            }
        });

        bupor.setText("*");
        bupor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buporActionPerformed(evt);
            }
        });

        budiv.setText("/");
        budiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budivActionPerformed(evt);
            }
        });

        busqrt.setText("SQRT");
        busqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busqrtActionPerformed(evt);
            }
        });

        bupot.setText("^");
        bupot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupotActionPerformed(evt);
            }
        });

        bulog.setText("Log");
        bulog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulogActionPerformed(evt);
            }
        });

        buparcua.setText("[ ]");
        buparcua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buparcuaActionPerformed(evt);
            }
        });

        buparred.setText("( )");
        buparred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buparredActionPerformed(evt);
            }
        });

        buguardar.setText("Guardar");
        buguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buguardarActionPerformed(evt);
            }
        });

        buCalcula.setText("Calcular");
        buCalcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buCalculaActionPerformed(evt);
            }
        });

        jTextAreaTot.setColumns(20);
        jTextAreaTot.setRows(5);
        jScrollPane1.setViewportView(jTextAreaTot);

        cmbparametro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbparametroItemStateChanged(evt);
            }
        });

        bupi.setText("PI");
        bupi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupiActionPerformed(evt);
            }
        });

        bucond.setText("SI(a>=b;1;2)");
        bucond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bucondActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addComponent(jScrollPane4)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bumas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bumenos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bupor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(budiv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(busqrt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bupot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bulog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buparcua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buparred)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bupi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbparametro, 0, 251, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buCalcula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buguardar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(bucond))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bumas)
                    .addComponent(bumenos)
                    .addComponent(bupor)
                    .addComponent(budiv)
                    .addComponent(busqrt)
                    .addComponent(bupot)
                    .addComponent(bulog)
                    .addComponent(buparcua)
                    .addComponent(buparred)
                    .addComponent(buCalcula)
                    .addComponent(buguardar)
                    .addComponent(cmbparametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bupi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bucond)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bumasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bumasActionPerformed
        // TODO add your handling code here:
        this.jTextAreaEdit.setText(this.jTextAreaEdit.getText() + "+");
        this.jTextAreaEdit.requestFocus();
    }//GEN-LAST:event_bumasActionPerformed

    private void bumenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bumenosActionPerformed
        // TODO add your handling code here:
        this.jTextAreaEdit.setText(this.jTextAreaEdit.getText() + "-");
        this.jTextAreaEdit.requestFocus();
    }//GEN-LAST:event_bumenosActionPerformed

    private void buporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buporActionPerformed
        // TODO add your handling code here:
        this.jTextAreaEdit.setText(this.jTextAreaEdit.getText() + "*");
        this.jTextAreaEdit.requestFocus();
    }//GEN-LAST:event_buporActionPerformed

    private void budivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budivActionPerformed
        // TODO add your handling code here:
        this.jTextAreaEdit.setText(this.jTextAreaEdit.getText() + "/");
        this.jTextAreaEdit.requestFocus();
    }//GEN-LAST:event_budivActionPerformed

    private void busqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busqrtActionPerformed
        // TODO add your handling code here:
        this.jTextAreaEdit.setText(this.jTextAreaEdit.getText() + "Math.sqrt(valor)");
        this.jTextAreaEdit.requestFocus();
    }//GEN-LAST:event_busqrtActionPerformed

    private void bupotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupotActionPerformed
        // TODO add your handling code here:
        this.jTextAreaEdit.setText(this.jTextAreaEdit.getText() + "Math.pow(valor,potencia)");
        this.jTextAreaEdit.requestFocus();
    }//GEN-LAST:event_bupotActionPerformed

    private void bulogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulogActionPerformed
        // TODO add your handling code here:
        this.jTextAreaEdit.setText(this.jTextAreaEdit.getText() + "Math.log(valor)/Math.log(10)");
        this.jTextAreaEdit.requestFocus();
    }//GEN-LAST:event_bulogActionPerformed

    private void buparcuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buparcuaActionPerformed
        // TODO add your handling code here:
        this.jTextAreaEdit.setText(this.jTextAreaEdit.getText() + "[]");
    }//GEN-LAST:event_buparcuaActionPerformed

    private void buparredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buparredActionPerformed
        // TODO add your handling code here:
        this.jTextAreaEdit.setText(this.jTextAreaEdit.getText() + "()");

    }//GEN-LAST:event_buparredActionPerformed

    private void buCalculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buCalculaActionPerformed
        // TODO add your handling code here:
        //Math.pow(9.04164151,-2)
        //número en E.5 notacion cientifica

        //double myvalue = 9.350430293/135584.0165;
        //System.out.println(new BigDecimal(myvalue).toPlainString()); 
        //Math.log(0.00011199) / Math.log(10);   -3.95082
        //Math.pow((1.14-2*Math.log(0.025/581+9.35/(1225901.87174689*(Math.pow(0.012232228199748,0.5))))/Math.log(10)),-2)
        //0.0122322281
        String msg = "";

        ScriptEngineManager manager = new ScriptEngineManager();
        ScriptEngine engine = manager.getEngineByName("js");

        engine.put("X", 3);

        String Formula = this.jTextAreaEdit.getText();
        Formula = Formula.replaceAll("valor", "3");
        Formula = Formula.replaceAll("potencia", "2");
        Formula = Formula.replaceAll(" ", "").trim();

        double operation = 0;
        String FormulaOri = Formula;

        CFormulaArma objfa = new CFormulaArma();
        operation = objfa.FormulaTotal(Formula);

        if (objfa.xError.equals("") == false) {
            JOptionPane.showMessageDialog(null, "Error en CFormulaArma: " + objfa.xError);
            return;
        }
        ///////////////

        System.out.println(this.jTextAreaEdit.getText());


            this.jTextAreaTot.setText(FormulaOri + "\n" + objfa.FormulaConv + "\nTotal : " + operation);

        this.FormulaValida = FormulaOri;

        //txttotal.setText(engine.eval(""));
    }//GEN-LAST:event_buCalculaActionPerformed

    private void buguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buguardarActionPerformed
        // TODO add your handling code here:
        if (this.FormulaValida.equals("") == false) {
            txFormula.setText(this.FormulaValida);
            this.setVisible(false);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Primero debe Calcular formula para validar");
        }
    }//GEN-LAST:event_buguardarActionPerformed

    private void cmbparametroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbparametroItemStateChanged
        // TODO add your handling code here:

        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String parametro = cmbparametro.getSelectedItem().toString();
            if (parametro.equals("") == true) {
                //JOptionPane.showMessageDialog(null, "Ingrese tipo de parametro");
                return;
            } else {
                parametro = parametro.substring(0, parametro.indexOf(" "));
                this.jTextAreaEdit.setText(this.jTextAreaEdit.getText() + "PR" + parametro);
            }
        }

    }//GEN-LAST:event_cmbparametroItemStateChanged

    private void bupiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupiActionPerformed
        // TODO add your handling code here:
        this.jTextAreaEdit.setText(this.jTextAreaEdit.getText() + "Math.PI");
    }//GEN-LAST:event_bupiActionPerformed

    private void bucondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bucondActionPerformed
        // TODO add your handling code here:
        this.jTextAreaEdit.setText(this.jTextAreaEdit.getText() + "SI( >= ; ; )"); 
    }//GEN-LAST:event_bucondActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CSistema objs = new CSistema();
                JTextArea txFormula = new JTextArea();
                new Formula(objs, txFormula).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buCalcula;
    private javax.swing.JButton bucond;
    private javax.swing.JButton budiv;
    private javax.swing.JButton buguardar;
    private javax.swing.JButton bulog;
    private javax.swing.JButton bumas;
    private javax.swing.JButton bumenos;
    private javax.swing.JButton buparcua;
    private javax.swing.JButton buparred;
    private javax.swing.JButton bupi;
    private javax.swing.JButton bupor;
    private javax.swing.JButton bupot;
    private javax.swing.JButton busqrt;
    private javax.swing.JComboBox<String> cmbparametro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextAreaEdit;
    private javax.swing.JTextArea jTextAreaIni;
    private javax.swing.JTextArea jTextAreaTot;
    // End of variables declaration//GEN-END:variables
}
