/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import clase.CParametro;
import clase.CSistema;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author assendofr
 */
public class Parametros extends javax.swing.JFrame {

    CSistema objs;
    DefaultTableModel amodel;
    String strMsg = "";

    /**
     * Creates new form Parametros
     */
    public Parametros(CSistema objs) {
        //cerrar form propiedad deafultcloseoperation : hide 
        initComponents();
        this.objs = objs;
        LlenaTabla();
        Cargar();
    }

    void LlenaTabla() {
        CParametro objt = new CParametro(0, "", 0, "", 0);
        amodel = objt.Listar();

        if (objt.xError.equals("") == true) {
            this.jTable1.setModel(amodel);
        } else {
            JOptionPane.showMessageDialog(null, "Error : \n" + objt.xError);
        }

        //
    }

    public void Cargar() {
        try {

            //llenar combo tipo
            CParametro objt = new CParametro(0, "", 0, "", 0);

            objt.LLenarTipo();

            if (objt.xError.equals("") == false) {
                JOptionPane.showMessageDialog(null, "Error : \n" + objt.xError);
                return;
            }

            String strDato = "";

            this.cmbtipo.addItem("");
            for (int x = 0; x < objt.strDatosCombo.length; x++) {
                strDato = objt.strDatosCombo[x];
                cmbtipo.addItem(strDato);
            }

            //llenar combo tabla
            objt.LLenarTabla();

            this.cmbtabla.addItem("");
            for (int x = 0; x < objt.strDatosCombo.length; x++) {
                strDato = objt.strDatosCombo[x];
                cmbtabla.addItem(strDato);
            }

        } catch (Exception ex) {
            strMsg = ex.getMessage();
            JOptionPane.showMessageDialog(null, strMsg);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblidparametro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbtipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbtabla = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtformula = new javax.swing.JTextArea();
        bunuevo = new javax.swing.JButton();
        buguardar = new javax.swing.JButton();
        bueliminar = new javax.swing.JButton();
        buformula = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("idparametro");

        lblidparametro.setText("0");

        jLabel2.setText("descripcion");

        jLabel3.setText("Tipo");

        jLabel4.setText("Tabla");

        jLabel5.setText("Formula");

        txtformula.setEditable(false);
        txtformula.setColumns(20);
        txtformula.setRows(5);
        jScrollPane2.setViewportView(txtformula);

        bunuevo.setText("Nuevo");
        bunuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bunuevoActionPerformed(evt);
            }
        });

        buguardar.setText("Guardar");
        buguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buguardarActionPerformed(evt);
            }
        });

        bueliminar.setText("Eliminar");
        bueliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bueliminarActionPerformed(evt);
            }
        });

        buformula.setText("Formula");
        buformula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buformulaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(buformula)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblidparametro, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdescripcion)
                            .addComponent(cmbtipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbtabla, 0, 243, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bunuevo)
                            .addComponent(buguardar)
                            .addComponent(bueliminar))
                        .addContainerGap())
                    .addComponent(jScrollPane2)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblidparametro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bunuevo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buguardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbtabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bueliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(14, 14, 14)
                        .addComponent(buformula)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        return;
    }//GEN-LAST:event_formWindowClosing

    private void bunuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bunuevoActionPerformed
        // TODO add your handling code here:
        Limpiar();

    }//GEN-LAST:event_bunuevoActionPerformed

    private void Limpiar() {
        this.lblidparametro.setText("0");
        this.txtdescripcion.setText("");
        this.txtformula.setText("");
        this.cmbtipo.setSelectedItem("");
        this.cmbtabla.setSelectedItem("");
    }
    
    private void buguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buguardarActionPerformed
        // TODO add your handling code here:
        if (this.txtdescripcion.getText().trim().equals("") == true) {
            JOptionPane.showMessageDialog(null, "Ingrese descripcion de parametro");
            return;
        }

        String tipo = cmbtipo.getSelectedItem().toString();
        if (tipo.equals("") == true) {
            JOptionPane.showMessageDialog(null, "Ingrese tipo de parametro");
            return;
        } else {
            tipo = tipo.substring(0, tipo.indexOf(" "));
        }

        String tabla = cmbtabla.getSelectedItem().toString();
        if (tabla.equals("") == true) {
            JOptionPane.showMessageDialog(null, "Ingrese tabla de parametro");
            return;

        } else {
            tabla = tabla.substring(0, tabla.indexOf(" "));
        }

        if (this.txtformula.getText().trim().equals("") == true) {
            JOptionPane.showMessageDialog(null, "Ingrese formula de parametro");
            return;
        }

        CParametro objt = new CParametro(Long.parseLong(this.lblidparametro.getText()),
                this.txtdescripcion.getText(),
                Long.parseLong(tipo),
                this.txtformula.getText().trim(),
                Long.parseLong(tabla));

        objt.Guardar();

        if (objt.xError.equals("") == true) {
            Limpiar();
            LlenaTabla();
            JOptionPane.showMessageDialog(null, "Parametro guardado correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "Error : \n" + objt.xError);
        }
        

    }//GEN-LAST:event_buguardarActionPerformed

    private void bueliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bueliminarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (Long.parseLong(this.lblidparametro.getText()) == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione parametro en lista");
            return;
        }

        CParametro objt = new CParametro(Long.parseLong(this.lblidparametro.getText()),
                "",
                0,
                "",
                0);

        objt.Eliminar();

        if (objt.xError.equals("") == true) {
            Limpiar();
            LlenaTabla();
            JOptionPane.showMessageDialog(null, "Parametro eliminado correctamente");
        } else {
            JOptionPane.showMessageDialog(null, "Error : \n" + objt.xError);
        }
    }//GEN-LAST:event_bueliminarActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        // TODO add your handling code here

        boolean a = jTable1.isEditing();
        if (a == false) {
            JOptionPane.showMessageDialog(null, "Tabla no es editable");
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        if (jTable1.getSelectedRow() != -1) {
            String idparametro = (String) amodel.getValueAt(jTable1.getSelectedRow(), 0);
            String descripcion = (String) amodel.getValueAt(jTable1.getSelectedRow(), 1);
            String idtipo = (String) amodel.getValueAt(jTable1.getSelectedRow(), 2);
            String tipo = (String) amodel.getValueAt(jTable1.getSelectedRow(), 3);
            String formula = (String) amodel.getValueAt(jTable1.getSelectedRow(), 4);
            String idtabla = (String) amodel.getValueAt(jTable1.getSelectedRow(), 5);
            String tabla = (String) amodel.getValueAt(jTable1.getSelectedRow(), 6);

            this.lblidparametro.setText(idparametro);
            this.txtdescripcion.setText(descripcion);

            this.cmbtipo.setSelectedItem(idtipo + " " + tipo);

            this.txtformula.setText(formula);

            this.cmbtabla.setSelectedItem(idtabla + " " + tabla);

        } else {
            System.out.println("Seleccione un renglon primero");
        }


    }//GEN-LAST:event_jTable1MouseClicked

    private void buformulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buformulaActionPerformed
        // TODO add your handling code here:
        JFrame frame = new Formula(objs, this.txtformula);
        AbrirForm(frame, 1000, 500, "Formula");
//        frame.setResizable(false);
    }//GEN-LAST:event_buformulaActionPerformed

    private void AbrirForm(JFrame frame, int A, int H, String Titulo) {
        //frame.setSize(A, H);
        frame.setLocationRelativeTo(null);//ubica form en medio
//        frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
////        frame.setResizable(false);//bloquea boton maximizar
        frame.setTitle(Titulo);
        frame.setIconImage(null);
        frame.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parametros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CSistema objs = new CSistema();
                new Parametros(objs).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bueliminar;
    private javax.swing.JButton buformula;
    private javax.swing.JButton buguardar;
    private javax.swing.JButton bunuevo;
    private javax.swing.JComboBox<String> cmbtabla;
    private javax.swing.JComboBox<String> cmbtipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblidparametro;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextArea txtformula;
    // End of variables declaration//GEN-END:variables
}
