/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import clase.CSistema;
import javax.swing.JFrame;

/**
 *
 * @author julio
 */
public class Principal extends javax.swing.JFrame {

    CSistema objs = new CSistema();
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.lblruta.setText("Base de datos sqlite : \n" + System.getProperty("user.dir")+ "/bdsqlite/db.bd");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bu_tablas = new javax.swing.JButton();
        bu_parametros = new javax.swing.JButton();
        lblruta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.red);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        bu_tablas.setText("Tablas");
        bu_tablas.setFocusable(false);
        bu_tablas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bu_tablas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bu_tablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_tablasActionPerformed(evt);
            }
        });

        bu_parametros.setText("Parametros");
        bu_parametros.setFocusable(false);
        bu_parametros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bu_parametros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bu_parametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bu_parametrosActionPerformed(evt);
            }
        });

        lblruta.setBackground(new java.awt.Color(58, 212, 47));
        lblruta.setText("jLabel1");

        jLabel1.setText("Base de datos es Sqlite se edita con sqlBrowser");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblruta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bu_tablas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bu_parametros)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bu_parametros)
                    .addComponent(bu_tablas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblruta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bu_tablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_tablasActionPerformed
        // TODO add your handling code here:
        JFrame frame = new Tablas(objs);
        AbrirForm(frame,1000 , 500,"Tablas");
//        frame.setResizable(false);
    }//GEN-LAST:event_bu_tablasActionPerformed

    private void bu_parametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bu_parametrosActionPerformed
        // TODO add your handling code here:
        JFrame frame = new Parametros(objs);
        AbrirForm(frame,1000 , 500,"Parametros");
//        frame.setResizable(false);
    }//GEN-LAST:event_bu_parametrosActionPerformed

    private void AbrirForm(JFrame frame, int A, int H, String Titulo)
    {
        //frame.setSize(A, H);
        frame.setLocationRelativeTo(null);//ubica form en medio
//        frame.setDefaultCloseOperation(frame.EXIT_ON_CLOSE);
////        frame.setResizable(false);//bloquea boton maximizar
        frame.setTitle(Titulo);
        frame.setIconImage(null);
        frame.setVisible(true);
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bu_parametros;
    private javax.swing.JButton bu_tablas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblruta;
    // End of variables declaration//GEN-END:variables
}
